os: windows
language: node_js
node_js:
    - lts/*

install:
- |-
    cd cantarus-polydeploy-client
    npm ci
    cd ..
    
script: powershell -NoProfile -ExecutionPolicy Bypass -NonInteractive -File ./package.ps1
